builds:
  - id: "ark-wallet"
    main: ./cmd/ark-wallet
    ldflags:
      - -s -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.date={{.Date}}'
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: ark-wallet

## flag the semver v**.**.**-<tag>.* as pre-release on Github
release:
  prerelease: auto

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github-native

archives:
  - id: ark-wallet
    format: binary
    builds:
      - ark-wallet
    name_template: "ark-wallet-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"

dockers:
  ###########################
  # tag latest & prerelease #
  ###########################

  #amd64
  - image_templates:
      - "ghcr.io/ArkLabsHQ/ark-wallet:{{ .Tag }}-amd64"
        # push always either release or prerelease with a docker tag with the semver only
    skip_push: "false"
    use: buildx
    ids:
      - ark-wallet
    dockerfile: goreleaser.Dockerfile
    # GOOS of the built binaries/packages that should be used.
    goos: linux
    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64
    # Template of the docker build flags.
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=ark-wallet"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=COMMIT={{.Commit}}"
      - "--build-arg=DATE={{.Date}}"
  - image_templates:
      - "ghcr.io/ArkLabsHQ/ark-wallet:{{ .Tag }}-arm64v8"
        # push always either release or prerelease with a docker tag with the semver only
    skip_push: "false"
    use: buildx
    ids:
      - ark-wallet
    dockerfile: goreleaser.Dockerfile
    # GOOS of the built binaries/packages that should be used.
    goos: linux
    # GOARCH of the built binaries/packages that should be used.
    goarch: arm64
    # Template of the docker build flags.
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=ark-wallet"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=COMMIT={{.Commit}}"
      - "--build-arg=DATE={{.Date}}"

docker_manifests:
  - name_template: ghcr.io/ArkLabsHQ/ark-wallet:{{ .Tag }}
    image_templates:
      - ghcr.io/ArkLabsHQ/ark-wallet:{{ .Tag }}-amd64
      - ghcr.io/ArkLabsHQ/ark-wallet:{{ .Tag }}-arm64v8
    skip_push: "false"

  - name_template: ghcr.io/ArkLabsHQ/ark-wallet:latest
    image_templates:
      - ghcr.io/ArkLabsHQ/ark-wallet:{{ .Tag }}-amd64
      - ghcr.io/ArkLabsHQ/ark-wallet:{{ .Tag }}-arm64v8
    skip_push: auto
  