services:
  arkd:
    container_name: arkd 
    build: 
      context: .
      dockerfile: arkd.Dockerfile
    restart: unless-stopped
    environment:
      - ARK_ROUND_INTERVAL=10
      - ARK_NETWORK=regtest
      - ARK_LOG_LEVEL=6
      - ARK_TX_BUILDER_TYPE=covenantless
      - ARK_ESPLORA_URL=http://chopsticks:3000
      - ARK_NEUTRINO_PEER=bitcoin:18444
      - ARK_NO_TLS=true
      - ARK_NO_MACAROONS=true
      - ARK_DATADIR=/app/data
      - ARK_ALLOW_ZERO_FEES=true
    ports:
      - "7070:7070"
    volumes:
      - type: tmpfs
        target: /app/data
  fulmine:
    container_name: fulmine
    depends_on:
      - arkd
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - FULMINE_ARK_SERVER=arkd:7070
      - FULMINE_ESPLORA_URL=http://chopsticks:3000
      - FULMINE_WITH_TLS=false
    ports:
      - "7000:7000"
      - "7001:7001"
    volumes:
      - type: tmpfs
        target: /app/data

networks:
  default:
    name: nigiri
    external: true
