services:
  arkd-wallet:
    build:
      context: .
      dockerfile: arkdwallet.Dockerfile
    container_name: arkd-wallet
    ports:
      - "6060:6060"
    environment:
      - ARKD_WALLET_ESPLORA_URL=http://chopsticks:3000
      - ARKD_WALLET_NEUTRINO_PEER=bitcoin:18444
      - ARKD_WALLET_NETWORK=regtest
    volumes:
      - type: tmpfs
        target: /app/data

  arkd:
    build:
      context: .
      dockerfile: arkd.Dockerfile
    container_name: arkd
    restart: unless-stopped
    depends_on:
      - arkd-wallet
    ports:
      - "7070:7070"
    environment:
      - ARKD_LOG_LEVEL=5
      - ARKD_NO_MACAROONS=true
      - ARKD_VTXO_TREE_EXPIRY=20
      - ARKD_SCHEDULER_TYPE=block
      - ARKD_UNILATERAL_EXIT_DELAY=512
      - ARKD_BOARDING_EXIT_DELAY=1024
      - ARKD_WALLET_ADDR=arkd-wallet:6060
      - ARKD_ESPLORA_URL=http://chopsticks:3000
      - ARKD_VTXO_MIN_AMOUNT=1
      - ARKD_LIVE_STORE_TYPE=inmemory
      - ARKD_EVENT_DB_TYPE=badger
      - ARKD_DB_TYPE=sqlite
    volumes:
      - type: tmpfs
        target: /app/data

  fulmine:
    container_name: fulmine
    depends_on:
      - arkd
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - FULMINE_ARK_SERVER=arkd:7070
      - FULMINE_ESPLORA_URL=http://chopsticks:3000
      - FULMINE_BOLTZ_URL=http://boltz:9001
      - FULMINE_BOLTZ_WS_URL=ws://boltz:9004
      - FULMINE_NO_MACAROONS=true
      - FULMINE_LOG_LEVEL=5
      - FULMINE_DISABLE_TELEMETRY=true
    ports:
      - "7000:7000"
      - "7001:7001"
    volumes:
      - type: tmpfs
        target: /app/data

networks:
  default:
    name: nigiri
    external: true
