services:
  pgnbxplorer:
    restart: unless-stopped
    image: postgres:16
    container_name: pgnbxplorer
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nbxplorer -h 127.0.0.1 -p 5432"]
      interval: 2s
      timeout: 2s
      retries: 30
  nbxplorer:
    restart: unless-stopped
    container_name: nbxplorer
    ports: 
      - 32838:32838
    image: nicolasdorier/nbxplorer:2.5.30
    environment:
      - NBXPLORER_NETWORK=regtest
      - NBXPLORER_CHAINS=btc
      - NBXPLORER_BTCRPCURL=http://bitcoin:18443
      - NBXPLORER_BTCNODEENDPOINT=bitcoin:18444
      - NBXPLORER_BTCRPCUSER=admin1
      - NBXPLORER_BTCRPCPASSWORD=123
      - NBXPLORER_VERBOSE=1
      - NBXPLORER_BIND=0.0.0.0:32838
      - NBXPLORER_TRIMEVENTS=10000
      - NBXPLORER_SIGNALFILESDIR=/datadir
      - NBXPLORER_POSTGRES=User ID=postgres;Host=pgnbxplorer;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorer
      - NBXPLORER_EXPOSERPC=1
      - NBXPLORER_NOAUTH=1
    volumes:
      - type: tmpfs
        target: /datadir
    depends_on:
      pgnbxplorer:
        condition: service_healthy
    
  arkd-wallet:
    restart: unless-stopped
    build:
      context: .
      dockerfile: arkdwallet.Dockerfile
    container_name: arkd-wallet
    depends_on:
      - nbxplorer
    ports:
      - "6060:6060"
    environment:
      - ARKD_WALLET_LOG_LEVEL=5
      - ARKD_WALLET_NBXPLORER_URL=http://nbxplorer:32838
      - ARKD_WALLET_NETWORK=regtest
      - ARKD_WALLET_SIGNER_KEY=1822f98b3a7366532d3a875fa94c97948fe8f6a71a0ca1e94587be5f4ce646d1
    volumes:
      - type: tmpfs
        target: /app/data
  arkd:
    build:
      context: .
      dockerfile: arkd.Dockerfile
    container_name: arkd
    restart: unless-stopped
    depends_on:
      - arkd-wallet
    ports:
      - "7070:7070"
    environment:
      - ARKD_LOG_LEVEL=6
      - ARKD_NO_MACAROONS=true
      - ARKD_VTXO_TREE_EXPIRY=20
      - ARKD_SCHEDULER_TYPE=block
      - ARKD_UNILATERAL_EXIT_DELAY=512
      - ARKD_BOARDING_EXIT_DELAY=1024
      - ARKD_CHECKPOINT_EXIT_DELAY=10
      - ARKD_WALLET_ADDR=arkd-wallet:6060
      - ARKD_ESPLORA_URL=http://chopsticks:3000
      - ARKD_VTXO_MIN_AMOUNT=1
      - ARKD_LIVE_STORE_TYPE=inmemory
      - ARKD_EVENT_DB_TYPE=badger
      - ARKD_DB_TYPE=sqlite
      - ARKD_ROUND_INTERVAL=10
    volumes:
      - type: tmpfs
        target: /app/data

  fulmine:
    container_name: fulmine
    depends_on:
      - arkd
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - FULMINE_ARK_SERVER=arkd:7070
      - FULMINE_ESPLORA_URL=http://chopsticks:3000
      - FULMINE_BOLTZ_URL=http://boltz:9001
      - FULMINE_BOLTZ_WS_URL=ws://boltz:9004
      - FULMINE_NO_MACAROONS=true
      - FULMINE_LOG_LEVEL=5
      - FULMINE_DISABLE_TELEMETRY=true
      - FULMINE_SWAP_TIMEOUT=30
    ports:
      - "7000:7000"
      - "7001:7001"
    volumes:
      - type: tmpfs
        target: /app/data

networks:
  default:
    name: nigiri
    external: true
