name: ci_integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ">1.17.2"
      - uses: actions/checkout@v3
      
      - run: go get -v -t -d ./...
      
      - name: Run Nigiri
        uses: vulpemventures/nigiri-github-action@v1
        with:
          use_liquid: false
          use_ln: false

      - name: Build test environment
        run: make build-test-env
      
      - name: Start test environment
        run: make up-test-env
      
      - name: Setup test environment
        run: make setup-test-env
      
      - name: Run integration tests
        run: make integrationtest
      
      - name: Cleanup test environment
        run: make down-test-env
        if: always()  # Run cleanup even if tests fail
  