name: ci_unit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.23.1'
      - uses: actions/checkout@v3
      - name: check linting
        uses: golangci/golangci-lint-action@v6
        with:
          args: '--timeout=180s --concurrency=4 --fast'
          version: v1.61
      - name: check code integrity
        uses: securego/gosec@master
        with:
          args: '-confidence medium -severity high -quiet ./...'
      - uses: bufbuild/buf-setup-action@v1.47.2
      - name: check proto linting
        run: buf lint --exclude-path ./api-spec/protobuf/cln
      - run: go get -v -t -d ./...
      - name: unit testing
        run: make test
