name: ci_unit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.23.1'
          cache: true
      
      # Run linting with the original working configuration
      - name: check linting
        uses: golangci/golangci-lint-action@v6
        with:
          args: '--timeout=180s --concurrency=4 --fast'
          version: v1.61
      
      - name: Get dependencies
        run: go get -v -t -d ./...
      
      - name: Run main tests
        run: make test

      - name: Run VHTLC tests
        run: cd pkg/vhtlc && go test -v -count=1 -race

      # Security check with minimal output
      - name: Security Check
        uses: securego/gosec@v2.22.2
        with:
          args: '-no-fail -confidence medium -severity high -quiet -exclude-dir=.git -exclude-dir=vendor -exclude-generated ./...'
